### ISSUE TITLE
"Edit this page" buttons have broken link

### ISSUE THREAD

**Issue by BobDotCom** [Pycord-Development/guide#51] opened 2022-03-20 18:18 UTC
**Describe the bug**

The buttons lead to a 404 on github

**To Reproduce**

Click the "Edit this page" button at the bottom of any docs page, and observe the GitHub 404. Can be reproduced on (but not limited to) the following: [Introduction](https://guide-preview.vincentrps.xyz/guide/#credits), [Installation](https://guide-preview.vincentrps.xyz/guide/installation#development-build), [Creating Your First Bot](https://guide-preview.vincentrps.xyz/guide/Getting-Started/creating-your-first-bot#how-do-i-add-components-such-as-buttons-and-dropdown-menus-to-my-bot), etc.

**Expected behavior**

It should not 404

**Screenshots**

https://user-images.githubusercontent.com/71356958/159176642-ac785f8a-e676-40f0-ab60-85c69b582c3a.mov

**Additional context**

n/a

**Checklist**

Let's make sure you've properly done due diligence when reporting this issue!

 - [x] This is an issue with the build, not a spelling or grammar mistake.
 - [x] I have the latest version of the guide.

**Comment by BruceCodesGithub** [comment] 2022-03-21 05:37
Couldn't reproduce on the latest version of the guide. Could you check if it is still an issue?

**Comment by BruceCodesGithub** [comment] 2022-03-21 05:39
Found out that it was fixed with 7ee2d0a3e32cfac6dc34f60a3a922f8c7e18d57c. Closing the issue.

**Closed by BruceCodesGithub** 2022-03-21 05:39 UTC
